version: '3.7'
services: 
  db:
    image: postgres:latest
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: filebox
      POSTGRES_PASSWORD: password
      TZ: 'GMT+8'
      PGTZ: 'GMT+8'
  redis:
    image: redis/redis-stack:latest
    restart: always
    entrypoint: redis-server --appendonly yes --maxmemory 512mb --maxmemory-policy allkeys-lru
    ports:
      - '6379:6379'
      
  filebox-server:
    build: .
    depends_on:
      - db
      - redis
    links:
      - db:db
      - redis:redis
    ports:
      - "8888:8888"
    environment:
      DATABASE_URL: 'postgres://postgres:password@db/filebox'
      HTTP_SERVER_ADDR: 'localhost:8888'
      UPLOAD_FILE_PATH: 'uploaded'
      GRACEFUL_SHUTDOWN_TIMEOUT_SEC: 5
      REDIS_CONN_ADDR: 'redis://redis'
      CODE_LEN: 5
      IP_VISIT_ERROR_LIMIT: 5
      IP_UPLOAD_LIMIT: 5
      IP_VISIT_ERROR_DURATION_DAY: 1
      ALLOWED_ORIGIN: 'http://127.0.0.1:5173'
